name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Upload Website to S3
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change if you're using another region

      - name: Sync files to S3
        run: |
          aws s3 sync ./public s3://elainigeffa.com --delete
